name: studypal_dev

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: postgres-studypal-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 500M
    command: >
      postgres -c shared_buffers=256MB
               -c work_mem=4MB
               -c max_connections=20
    networks:
      - network-studypal-dev

volumes:
  postgres-data-dev:
    driver: local
    driver_opts:
        type: tmpfs
        device: tmpfs

networks:
  network-studypal-dev:
    driver: bridge
