name: studypal_dev

services:
  redis:
    image: redis:7.2
    restart: unless-stopped
    container_name: redis-studypal-dev
    ports:
      - "6380:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - network-studypal-dev

volumes:
  redis-data-dev:

networks:
  network-studypal-dev:
    driver: bridge
