app:
  caches:
    cacheSpecs:
      register:
        ttl: PT10M
        maxSize: 1000
      resetPassword:
        ttl: PT5M
        maxSize: 1000
      verificationCodes:
        ttl: PT5M
        maxSize: 100
      accessTokens:
        ttl: PT1H
        maxSize: 1000
      refreshTokens:
        ttl: P7D
        maxSize: 1000
      userSummary:
        ttl: PT15M
        maxSize: 500
      userTeams:
        ttl: PT15M
        maxSize: 1000
      teamDashboard:
        ttl: PT15M
        maxSize: 1000
      teamMembers:
        ttl: PT15M
        maxSize: 1000
      invitations:
        ttl: PT10M
        maxSize: 1000
      notifications:
        ttl: PT10M
        maxSize: 1000